<?php declare(strict_types=1); ?>
<style>
.rep-page{width:100%;max-width:100%;min-width:0;margin:0 auto;padding:10px 0 42px;box-sizing:border-box}.rep-panel{width:100%;overflow:hidden;border:1px solid #dbe5f0;border-radius:18px;background:#fff;box-shadow:0 15px 40px rgba(15,35,65,.08)}
.rep-header{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:23px 25px;border-bottom:1px solid #e2e8f0;background:linear-gradient(135deg,#fff,#f7fbff)}.rep-header>div:first-child{min-width:0;flex:1}.rep-header h1{margin:0 0 6px;color:#08264f;font-size:25px}.rep-header p{margin:0;color:#64748b;font-size:14px;line-height:1.55}
.rep-actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.rep-btn{display:inline-flex;align-items:center;justify-content:center;min-height:41px;padding:9px 15px;border:0;border-radius:10px;font:inherit;font-size:13px;font-weight:800;text-decoration:none;cursor:pointer;white-space:nowrap}.rep-btn-primary{background:#2563eb;color:#fff}.rep-btn-secondary{background:#e9eef5;color:#334155}.rep-btn-success{background:#059669;color:#fff}.rep-btn-dark{background:#0f2747;color:#fff}
.rep-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;padding:20px 24px}.rep-stat{padding:17px;border:1px solid #e2e8f0;border-radius:13px;background:#f8fafc}.rep-stat span{display:block;margin-bottom:6px;color:#64748b;font-size:11px;font-weight:800;text-transform:uppercase}.rep-stat strong{display:block;color:#0f2747;font-size:25px}
.rep-modules{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;padding:0 24px 24px}.rep-module{display:flex;align-items:center;gap:16px;padding:20px;border:1px solid #e2e8f0;border-radius:14px;background:#fff;color:inherit;text-decoration:none;transition:.15s ease}.rep-module:hover{box-shadow:0 12px 25px rgba(15,35,65,.10);transform:translateY(-2px)}.rep-module-icon{display:grid;width:52px;height:52px;flex:0 0 52px;place-items:center;border-radius:14px;background:#eff6ff;font-size:25px}.rep-module h2{margin:0 0 5px;color:#0f2747;font-size:18px}.rep-module p{margin:0;color:#64748b;font-size:13px;line-height:1.5}
.rep-toolbar{display:flex;align-items:end;justify-content:space-between;gap:14px;padding:17px 24px;border-bottom:1px solid #e8eef5;background:#fbfdff}.rep-filter{display:grid;grid-template-columns:minmax(145px,1fr) minmax(145px,1fr) minmax(190px,1.5fr) auto;gap:10px;align-items:end;flex:1;min-width:0}.rep-field{display:grid;gap:6px;min-width:0}.rep-field label{color:#475569;font-size:11px;font-weight:800;text-transform:uppercase}.rep-field input,.rep-field select{width:100%;min-width:0;min-height:41px;padding:9px 11px;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:9px;background:#fff;color:#0f172a;font:inherit;font-size:13px;outline:none}.rep-count{white-space:nowrap;color:#475569;font-size:13px;font-weight:800}
.rep-content{width:100%;min-width:0;padding:22px 24px 27px;box-sizing:border-box}.rep-table-wrap{width:100%;min-width:0;overflow-x:auto;border:1px solid #e2e8f0;border-radius:12px}.rep-table{width:100%;min-width:900px;border-collapse:collapse}.rep-table th,.rep-table td{padding:12px 11px;border-bottom:1px solid #e8eef5;text-align:left;vertical-align:middle;font-size:12px;line-height:1.45}.rep-table th{background:#f8fafc;color:#334155;font-weight:800;white-space:nowrap}.rep-table tbody tr:hover{background:#f8fbff}.rep-main{display:block;color:#0f2747;font-weight:800}.rep-sub{display:block;margin-top:3px;color:#64748b;font-size:11px}
.rep-badge{display:inline-flex;align-items:center;min-height:26px;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:800;white-space:nowrap}.rep-blue{background:#eff6ff;color:#1d4ed8}.rep-green{background:#ecfdf5;color:#047857}.rep-yellow{background:#fffbeb;color:#b45309}.rep-red{background:#fff1f2;color:#be123c}.rep-empty{padding:45px 20px;border:1px dashed #cbd5e1;border-radius:13px;background:#fbfdff;text-align:center}.rep-empty span{display:block;margin-bottom:10px;font-size:36px}.rep-empty h2{margin:0 0 7px;color:#0f2747;font-size:20px}.rep-empty p{margin:0;color:#64748b}.rep-alert{margin:18px 24px 0;padding:13px 15px;border:1px solid #fecaca;border-radius:10px;background:#fff1f2;color:#991b1b;font-size:13px;font-weight:700}.rep-footer-note{padding:0 24px 22px;color:#64748b;font-size:12px;text-align:right}
@media(max-width:1000px){.rep-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.rep-filter{grid-template-columns:repeat(2,minmax(0,1fr))}.rep-toolbar{align-items:stretch;flex-direction:column}.rep-count{align-self:flex-end}}@media(max-width:700px){.rep-header{align-items:stretch;flex-direction:column}.rep-actions{width:100%}.rep-actions .rep-btn{flex:1}.rep-stats,.rep-modules{grid-template-columns:1fr}.rep-filter{grid-template-columns:1fr}.rep-header,.rep-toolbar,.rep-content{padding-left:16px;padding-right:16px}.rep-stats,.rep-modules{padding-left:16px;padding-right:16px}}
@media print{body *{visibility:hidden}.rep-page,.rep-page *{visibility:visible}.rep-page{position:absolute;inset:0;width:100%;padding:0}.rep-panel{border:0;box-shadow:none}.rep-actions,.rep-toolbar{display:none!important}.rep-header{padding:0 0 14px}.rep-content{padding:12px 0 0}.rep-table-wrap{overflow:visible;border:0}.rep-table{min-width:0}.rep-table th,.rep-table td{padding:6px;font-size:9px}}
</style>
